### ISSUE TITLE
Panicing due to: runtime error: invalid memory address or nil pointer dereference (createAvalancheChain)

### ISSUE THREAD

**Issue by fabiux82** [ava-labs/gecko#114]
Gecko node crashed with log below:
OS: Ubuntu 18.04

```
FATAL[04-24|11:21:02] <chain 4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM> /utils/logging/log.go#247: Panicing due to:
runtime error: invalid memory address or nil pointer dereference
From:                                                                                                                                                     [32/99657]
goroutine 105 [running]:
github.com/ava-labs/gecko/utils/logging.Stacktrace.String(0x450a00, 0xc000a8b301, 0x7f9aa3890b88)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/stack.go:20 +0x71
fmt.(*pp).handleMethods(0xc00678c820, 0x73, 0x6400000001)
        /usr/local/go/src/fmt/print.go:630 +0x302
fmt.(*pp).printArg(0xc00678c820, 0xddb5a0, 0xc005e8b140, 0x73)
        /usr/local/go/src/fmt/print.go:713 +0x206
fmt.(*pp).doPrintf(0xc00678c820, 0xef7362, 0x1c, 0xc000a8b8c0, 0x2, 0x2)
        /usr/local/go/src/fmt/print.go:1030 +0x15b
fmt.Sprintf(0xef7362, 0x1c, 0xc000a8b8c0, 0x2, 0x2, 0xc006064d20, 0x46)
        /usr/local/go/src/fmt/print.go:219 +0x66
github.com/ava-labs/gecko/utils/logging.(*Log).format(0xc0007fc840, 0x1, 0xef7362, 0x1c, 0xc000a8b8c0, 0x2, 0x2, 0x1, 0xc005e8b140)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:165 +0x11a
github.com/ava-labs/gecko/utils/logging.(*Log).log(0xc0007fc840, 0x1, 0xef7362, 0x1c, 0xc000a8b8c0, 0x2, 0x2)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:138 +0x11f
github.com/ava-labs/gecko/utils/logging.(*Log).Fatal(...)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:180
github.com/ava-labs/gecko/utils/logging.(*Log).StopOnPanic(0xc0007fc840)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:247 +0xf4
panic(0xd9a520, 0x19a3b20)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/ava-labs/gecko/snow/engine/avalanche/state.(*uniqueVertex).Parents(0xc0060514a0, 0x30, 0x30, 0xc00606e9c0)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/state/unique_vertex.go:111 +0x3c
github.com/ava-labs/gecko/snow/engine/avalanche.(*vertexJob).MissingDependencies(0xc00606e9c0, 0x42f258)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/vertex_job.go:40 +0x46
github.com/ava-labs/gecko/snow/engine/common/queue.(*Jobs).Push(0xc0008630e0, 0x1160180, 0xc00606e9c0, 0x1, 0x0)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/common/queue/jobs.go:49 +0x35
github.com/ava-labs/gecko/snow/engine/avalanche.(*bootstrapper).storeVertex(0xc0000352e8, 0x1169c60, 0xc0023c2b00)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/bootstrapper.go:163 +0x39f
github.com/ava-labs/gecko/snow/engine/avalanche.(*bootstrapper).addVertex(0xc0000352e8, 0x1169c60, 0xc0023c2b00)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/bootstrapper.go:141 +0x3f
github.com/ava-labs/gecko/snow/engine/avalanche.(*bootstrapper).Put(0xc0000352e8, 0xc00084e320, 0xc276, 0xc002fd04a0, 0xc00185ea48, 0x54, 0x54)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/bootstrapper.go:106 +0x2a4
github.com/ava-labs/gecko/snow/engine/avalanche.(*Transitive).Put(0xc000035200, 0xc00084e320, 0xc276, 0xc002fd04a0, 0xc00185ea48, 0x54, 0x54)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/transitive.go:87 +0x2e2
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).dispatchMsg(0xc000863fb0, 0x8, 0xc00084e320, 0xc276, 0xc002fd04a0, 0xc00185ea48, 0x54, 0x54, 0x0, 0x0, 
...)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:83 +0x434
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).Dispatch(0xc000863fb0)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:43 +0x2b3
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc0007fc840, 0xc0008556b0)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/chains.(*manager).createAvalancheChain
        /home/us/gopath/src/github.com/ava-labs/gecko/chains/manager.go:438 +0x8a2

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9b16ac]

goroutine 105 [running]:
github.com/ava-labs/gecko/utils/logging.(*Log).StopOnPanic(0xc0007fc840)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:249 +0x11d
panic(0xd9a520, 0x19a3b20)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/ava-labs/gecko/snow/engine/avalanche/state.(*uniqueVertex).Parents(0xc0060514a0, 0x30, 0x30, 0xc00606e9c0)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/state/unique_vertex.go:111 +0x3c
github.com/ava-labs/gecko/snow/engine/avalanche.(*vertexJob).MissingDependencies(0xc00606e9c0, 0x42f258)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/vertex_job.go:40 +0x46
github.com/ava-labs/gecko/snow/engine/common/queue.(*Jobs).Push(0xc0008630e0, 0x1160180, 0xc00606e9c0, 0x1, 0x0)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/common/queue/jobs.go:49 +0x35
github.com/ava-labs/gecko/snow/engine/avalanche.(*bootstrapper).storeVertex(0xc0000352e8, 0x1169c60, 0xc0023c2b00)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/bootstrapper.go:163 +0x39f
github.com/ava-labs/gecko/snow/engine/avalanche.(*bootstrapper).addVertex(0xc0000352e8, 0x1169c60, 0xc0023c2b00)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/bootstrapper.go:141 +0x3f
github.com/ava-labs/gecko/snow/engine/avalanche.(*bootstrapper).Put(0xc0000352e8, 0xc00084e320, 0xc276, 0xc002fd04a0, 0xc00185ea48, 0x54, 0x54)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/bootstrapper.go:106 +0x2a4
github.com/ava-labs/gecko/snow/engine/avalanche.(*Transitive).Put(0xc000035200, 0xc00084e320, 0xc276, 0xc002fd04a0, 0xc00185ea48, 0x54, 0x54)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/transitive.go:87 +0x2e2
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).dispatchMsg(0xc000863fb0, 0x8, 0xc00084e320, 0xc276, 0xc002fd04a0, 0xc00185ea48, 0x54, 0x54, 0x0, 0x0,
...)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:83 +0x434
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).Dispatch(0xc000863fb0)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:43 +0x2b3
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc0007fc840, 0xc0008556b0)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/chains.(*manager).createAvalancheChain
        /home/us/gopath/src/github.com/ava-labs/gecko/chains/manager.go:438 +0x8a2
```

**Comment by danlaine** [comment]
Hi @fabiux82 have you seen this issue on version 0.5.5 or 0.5.7?

**Comment by danlaine** [comment]
Closing for now. Let me know if you see this again.
