### ISSUE TITLE
When starting gecko it throws an error

### ISSUE THREAD

**Issue by thearchitectt** [ava-labs/gecko#297]
**Describe the bug**
When starting gecko it throws an error

**To Reproduce**
```
ava --http-host=<public_ip> --http-port=9650 --public-ip=<public_ip> --staking-port=9651 --db-dir=db/node1 --staking-tls-enabled=false
```

**Expected behavior**
Gecko should start

**Screenshots**
```
  ___       ________               __            ___
 / _ \_/\  /  _____/  ____   ____ |  | ______   / _ \_/\
 \/ \___/ /   \  ____/ __ \_/ ___\|  |/ /  _ \  \/ \___/
          \    \_\  \  ___/\  \___|    <  <_> )
           \______  /\___  >\___  >__|_ \____/
                  \/     \/     \/     \/
WARN [07-20|20:28:48] /main/main.go#45: Staking is disabled. Sybil control is not enforced.
WARN [07-20|20:28:48] /main/main.go#74: NAT traversal has failed. The node will be able to connect to less nodes.
INFO [07-20|20:28:48] /node/node.go#585: Gecko version is: avalanche/0.5.7
INFO [07-20|20:28:48] /node/node.go#282: Set node's ID to 7vm8PSQG7CGm7h95RtJScdKj2gpLx3Tj
INFO [07-20|20:28:48] /node/node.go#395: Initializing API server
INFO [07-20|20:28:48] /node/node.go#448: initializing keystore
INFO [07-20|20:28:48] /node/node.go#456: initializing keystore API
INFO [07-20|20:28:48] /api/server.go#106: adding route /ext/keystore
INFO [07-20|20:28:48] /node/node.go#472: initializing metrics API
INFO [07-20|20:28:48] /api/server.go#106: adding route /ext/metrics
INFO [07-20|20:28:48] /node/node.go#440: initializing SharedMemory
FATAL[07-20|20:28:48] /node/node.go#409: API server initialization failed with listen tcp <public_ip>:9650: bind: cannot assign requested address
FATAL[07-20|20:28:48] /utils/logging/log.go#247: Panicing due to:
runtime error: invalid memory address or nil pointer dereference
From:
goroutine 33 [running]:
github.com/ava-labs/gecko/utils/logging.Stacktrace.String(0x42fa00, 0xc000065801, 0x7f963941fc40)
        /opt/go/src/github.com/ava-labs/gecko/utils/logging/stack.go:20 +0x71
fmt.(*pp).handleMethods(0xc0002e01a0, 0x73, 0x6400000001)
        /usr/local/go/src/fmt/print.go:630 +0x302
fmt.(*pp).printArg(0xc0002e01a0, 0xdae060, 0xc00026ed38, 0x73)
        /usr/local/go/src/fmt/print.go:713 +0x206
fmt.(*pp).doPrintf(0xc0002e01a0, 0xecd978, 0x1c, 0xc000065df8, 0x2, 0x2)
        /usr/local/go/src/fmt/print.go:1030 +0x15b
fmt.Sprintf(0xecd978, 0x1c, 0xc000065df8, 0x2, 0x2, 0xc000036300, 0x3e)
        /usr/local/go/src/fmt/print.go:219 +0x66
github.com/ava-labs/gecko/utils/logging.(*Log).format(0xc0001020c0, 0x1, 0xecd978, 0x1c, 0xc000065df8, 0x2, 0x2, 0x1, 0x47c002)
        /opt/go/src/github.com/ava-labs/gecko/utils/logging/log.go:165 +0x11a
github.com/ava-labs/gecko/utils/logging.(*Log).log(0xc0001020c0, 0x1, 0xecd978, 0x1c, 0xc000065df8, 0x2, 0x2)
        /opt/go/src/github.com/ava-labs/gecko/utils/logging/log.go:138 +0x11f
github.com/ava-labs/gecko/utils/logging.(*Log).Fatal(...)
        /opt/go/src/github.com/ava-labs/gecko/utils/logging/log.go:180
github.com/ava-labs/gecko/utils/logging.(*Log).StopOnPanic(0xc0001020c0)
        /opt/go/src/github.com/ava-labs/gecko/utils/logging/log.go:247 +0xf4
panic(0xd6b8c0, 0x189a9e0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/ava-labs/gecko/node.(*Node).initAPIServer.func1()
        /opt/go/src/github.com/ava-labs/gecko/node/node.go:410 +0x12b
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc0001020c0, 0xc000040df0)
        /opt/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/node.(*Node).initAPIServer
        /opt/go/src/github.com/ava-labs/gecko/node/node.go:399 +0x119

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xc0419b]
goroutine 33 [running]:
github.com/ava-labs/gecko/utils/logging.(*Log).StopOnPanic(0xc0001020c0)
        /opt/go/src/github.com/ava-labs/gecko/utils/logging/log.go:249 +0x11d
panic(0xd6b8c0, 0x189a9e0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/ava-labs/gecko/node.(*Node).initAPIServer.func1()
        /opt/go/src/github.com/ava-labs/gecko/node/node.go:410 +0x12b
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc0001020c0, 0xc000040df0)
        /opt/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/node.(*Node).initAPIServer
        /opt/go/src/github.com/ava-labs/gecko/node/node.go:399 +0x119
```

**Operating System**
Ubuntu 18.04

**Additional context**
Freshly built and installed on a Ubuntu 18.04 server in GCP

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by aaronbuchwald** [comment]
Thanks for bringing this up @thearchitectt . This is caused by the port that the API server attempts to listen on already being occupied. We've fixed this error in the upcoming release so that it does not result in a panic, but it will still terminate and require that you specify an available port.

To fix this error in the meantime, you can specify an http port that is not occupied.

**Comment by thearchitectt** [comment]
Hi @aaronbuchwald,

Thanks for getting back to me.

I thought that might have been the case but `sudo lsof -i :9650` or `sudo lsof -i :9651` doesn't return the port to be in use.

Any further ideas?

**Comment by thearchitectt** [comment]
Hey @aaronbuchwald just wondering if you had any update on this? I still can't get it to work

**Comment by aaronbuchwald** [comment]
Hey @thearchitectt , sorry for the delay in getting back to you. It looks like this is the result of it not being able to listen on the public ip because it's behind a local network. @0x486F626F should we do NAT traversal for the http port as well to handle this case?

**Comment by aaronbuchwald** [comment]
@thearchitectt update on this, you can leave it blank ie. ```--http-host= ``` in order to make it public and do not use the flag or specify localhost to keep it only accessible locally.

**Comment by thearchitectt** [comment]
Hey @aaronbuchwald ! That worked perfectly thank you! Will you guys be working on a patch to not leave this flag empty?

**Comment by aaronbuchwald** [comment]
@thearchitectt this is actually coming from a somewhat unexpected behavior in the net package's Listen function. The http host and http port are passed into this function, and it is not able to bind to the public IP address.

There are a number of different valid IPs that a user might want to specify here besides just localhost, so we will leave the flag as is to provide that flexibility and clarify the documentation.

**Comment by thearchitectt** [comment]
@aaronbuchwald how interesting and quirky! Thanks for explaining.
