### ISSUE TITLE
Potential deadlock in VM shutdown

### ISSUE THREAD

**Issue by StephenButtolph** [ava-labs/gecko#66]
**Describe the bug**
Many of the current VM implementations have a potential deadlock during the `vm.Shutdown()` call. Specifically:

- [ ] [AVM](https://github.com/ava-labs/gecko/blob/master/vms/avm/vm.go#L201)
- [ ] [PlatformVM](https://github.com/ava-labs/gecko/blob/master/vms/platformvm/vm.go#L385)
- [ ] [SPChainVM](https://github.com/ava-labs/gecko/blob/master/vms/spchainvm/vm.go#L121)
- [ ] [SPDAGVM](https://github.com/ava-labs/gecko/blob/master/vms/spdagvm/vm.go#L133)

`ctx.Lock` is held while calling `timer.Stop()`. However, the function the timer is executing attempts to grab `ctx.Lock`. `timer.Stop()` is designed to ensure that the function will not be called after returning, this is a potential deadlock.

**Expected behavior**
Calling Shutdown on a VM should return timely.

**Fix**
The linked lines of code should be replaced with:
```(golang)
// There is a potential deadlock if the timer is about to execute a timeout.
// So, the lock must be released before stopping the timer.
vm.ctx.Lock.Unlock()
vm.timer.Stop()
vm.ctx.Lock.Lock()
```

**Comment by moreati** [comment]
The branch https://github.com/moreati/gecko/tree/deadlock-go might be of use. It replaces all uses of the `sync` package with uses of https://github.com/sasha-s/go-deadlock. go-deadlock can (sometimes) detect them, and print out a diagnostic. Here's what I got, only the third attempt triggered the diagnostic

```
:~/.local … thub.com/ava-labs/gecko deadlock-go+± ./scripts/build_test.sh 
ok      github.com/ava-labs/gecko/api   1.013s  coverage: 63.6% of statements
?       github.com/ava-labs/gecko/api/admin     [no test files]
...
?       github.com/ava-labs/gecko/xputtest/chainwallet  [no test files]
?       github.com/ava-labs/gecko/xputtest/dagwallet    [no test files]

:~/.local … thub.com/ava-labs/gecko deadlock-go+± ./scripts/build_test.sh 
ok      github.com/ava-labs/gecko/api   1.014s  coverage: 63.6% of statements
?       github.com/ava-labs/gecko/api/admin     [no test files]
...
?       github.com/ava-labs/gecko/xputtest/chainwallet  [no test files]
?       github.com/ava-labs/gecko/xputtest/dagwallet    [no test files]

:~/.local … thub.com/ava-labs/gecko deadlock-go+± ./scripts/build_test.sh 
ok      github.com/ava-labs/gecko/api   1.012s  coverage: 63.6% of statements
?       github.com/ava-labs/gecko/api/admin     [no test files]
?       github.com/ava-labs/gecko/api/ipcs      [no test files]
# github.com/ava-labs/go-ethereum/vendor/gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
ok      github.com/ava-labs/gecko/api/keystore  4.463s  coverage: 77.8% of statements
?       github.com/ava-labs/gecko/api/metrics   [no test files]
ok      github.com/ava-labs/gecko/cache 1.012s  coverage: 100.0% of statements
?       github.com/ava-labs/gecko/chains        [no test files]
ok      github.com/ava-labs/gecko/chains/atomic 1.022s  coverage: 97.8% of statements
?       github.com/ava-labs/gecko/database      [no test files]
ok      github.com/ava-labs/gecko/database/encdb        1.023s  coverage: 92.2% of statements
ok      github.com/ava-labs/gecko/database/leveldb      2.342s  coverage: 94.6% of statements
ok      github.com/ava-labs/gecko/database/memdb        1.017s  coverage: 100.0% of statements
ok      github.com/ava-labs/gecko/database/mockdb       1.007s  coverage: 70.3% of statements
?       github.com/ava-labs/gecko/database/nodb [no test files]
ok      github.com/ava-labs/gecko/database/prefixdb     1.096s  coverage: 100.0% of statements
ok      github.com/ava-labs/gecko/database/versiondb    1.031s  coverage: 98.3% of statements
ok      github.com/ava-labs/gecko/genesis       2.055s  coverage: 86.0% of statements
ok      github.com/ava-labs/gecko/ids   8.870s  coverage: 79.1% of statements
?       github.com/ava-labs/gecko/main  [no test files]
?       github.com/ava-labs/gecko/networking    [no test files]
?       github.com/ava-labs/gecko/networking/xputtest   [no test files]
?       github.com/ava-labs/gecko/node  [no test files]
?       github.com/ava-labs/gecko/snow  [no test files]
ok      github.com/ava-labs/gecko/snow/choices  1.037s  coverage: 48.4% of statements
ok      github.com/ava-labs/gecko/snow/consensus/avalanche      1.069s  coverage: 99.0% of statements
ok      github.com/ava-labs/gecko/snow/consensus/snowball       4.163s  coverage: 100.0% of statements
ok      github.com/ava-labs/gecko/snow/consensus/snowman        3.829s  coverage: 99.5% of statements
ok      github.com/ava-labs/gecko/snow/consensus/snowstorm      5.130s  coverage: 99.5% of statements
ok      github.com/ava-labs/gecko/snow/engine/avalanche 1.253s  coverage: 85.9% of statements
?       github.com/ava-labs/gecko/snow/engine/avalanche/state   [no test files]
?       github.com/ava-labs/gecko/snow/engine/common    [no test files]
ok      github.com/ava-labs/gecko/snow/engine/common/queue      1.039s  coverage: 80.1% of statements
ok      github.com/ava-labs/gecko/snow/engine/snowman   1.122s  coverage: 82.2% of statements
ok      github.com/ava-labs/gecko/snow/events   1.039s  coverage: 73.1% of statements
?       github.com/ava-labs/gecko/snow/networking       [no test files]
?       github.com/ava-labs/gecko/snow/networking/handler       [no test files]
?       github.com/ava-labs/gecko/snow/networking/router        [no test files]
ok      github.com/ava-labs/gecko/snow/networking/sender        1.013s  coverage: 12.8% of statements
ok      github.com/ava-labs/gecko/snow/networking/timeout       1.060s  coverage: 100.0% of statements
?       github.com/ava-labs/gecko/snow/triggers [no test files]
ok      github.com/ava-labs/gecko/snow/validators       1.016s  coverage: 81.6% of statements
ok      github.com/ava-labs/gecko/utils 1.014s  coverage: 59.1% of statements
ok      github.com/ava-labs/gecko/utils/crypto  8.824s  coverage: 38.3% of statements
ok      github.com/ava-labs/gecko/utils/formatting      1.009s  coverage: 93.5% of statements
?       github.com/ava-labs/gecko/utils/hashing [no test files]
?       github.com/ava-labs/gecko/utils/json    [no test files]
?       github.com/ava-labs/gecko/utils/logging [no test files]
ok      github.com/ava-labs/gecko/utils/math    1.010s  coverage: 100.0% of statements
ok      github.com/ava-labs/gecko/utils/random  1.025s  coverage: 95.5% of statements
ok      github.com/ava-labs/gecko/utils/timer   1.016s  coverage: 66.7% of statements
?       github.com/ava-labs/gecko/utils/units   [no test files]
ok      github.com/ava-labs/gecko/utils/wrappers        1.010s  coverage: 61.2% of statements
?       github.com/ava-labs/gecko/vms   [no test files]
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 3528 lock 0xc000134038
vm_test.go:174 avm.GenesisVM { ctx.Lock.Lock() } <<<<<
service_test.go:17 avm.setup { genesisBytes, _, vm := GenesisVM(t) }
service_test.go:17 avm.setup { genesisBytes, _, vm := GenesisVM(t) }

Have been trying to lock it again for more than 30s
goroutine 3821 lock 0xc000134038

Here is what goroutine 3528 doing now
goroutine 3528 [semacquire]:
sync.runtime_Semacquire(0xc0004adbe0)
        /usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0004adbd8)
        /usr/local/go/src/sync/waitgroup.go:130 +0xb1
github.com/ava-labs/gecko/utils/timer.(*Timer).Stop(0xc0004adbc0)
        /home/alex/.local/go/src/github.com/ava-labs/gecko/utils/timer/timer.go:66 +0xe2
github.com/ava-labs/gecko/vms/avm.(*VM).Shutdown(0xc0002d32b0)
        /home/alex/.local/go/src/github.com/ava-labs/gecko/vms/avm/vm.go:201 +0x6d
github.com/ava-labs/gecko/vms/avm.TestCreateFixedCapAsset(0xc000164400)
        /home/alex/.local/go/src/github.com/ava-labs/gecko/vms/avm/service_test.go:236 +0x494
testing.tRunner(0xc000164400, 0xc55078)
        /usr/local/go/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:960 +0x652

FAIL    github.com/ava-labs/gecko/vms/avm       30.763s
ok      github.com/ava-labs/gecko/vms/components/ava    1.063s  coverage: 26.4% of statements
ok      github.com/ava-labs/gecko/vms/components/codec  1.758s  coverage: 85.1% of statements
?       github.com/ava-labs/gecko/vms/components/core   [no test files]
ok      github.com/ava-labs/gecko/vms/components/missing        1.009s  coverage: 100.0% of statements
ok      github.com/ava-labs/gecko/vms/components/state  1.013s  coverage: 46.5% of statements
ok      github.com/ava-labs/gecko/vms/components/verify 1.006s  coverage: 100.0% of statements
ok      github.com/ava-labs/gecko/vms/evm       1.112s  coverage: 0.7% of statements
ok      github.com/ava-labs/gecko/vms/nftfx     1.064s  coverage: 100.0% of statements
ok      github.com/ava-labs/gecko/vms/platformvm        3.565s  coverage: 53.1% of statements
ok      github.com/ava-labs/gecko/vms/propertyfx        1.112s  coverage: 100.0% of statements
ok      github.com/ava-labs/gecko/vms/secp256k1fx       1.095s  coverage: 96.8% of statements
ok      github.com/ava-labs/gecko/vms/spchainvm 2.087s  coverage: 62.4% of statements
ok      github.com/ava-labs/gecko/vms/spdagvm   2.256s  coverage: 59.7% of statements
ok      github.com/ava-labs/gecko/vms/timestampvm       1.051s  coverage: 59.6% of statements
?       github.com/ava-labs/gecko/xputtest      [no test files]
ok      github.com/ava-labs/gecko/xputtest/avmwallet    1.072s  coverage: 63.9% of statements
?       github.com/ava-labs/gecko/xputtest/chainwallet  [no test files]
?       github.com/ava-labs/gecko/xputtest/dagwallet    [no test files]
FAIL
```

**Comment by moreati** [comment]
Some clarifying questions

1. Does it indicate an error or a bug has occurred if `vm.Ctx.Lock` is still held when `vm.Shutdown()` is called?
2. Several tests (e.g. [TestInvalidGenesis](https://github.com/ava-labs/gecko/blob/e5252c13e2df5c027852c08c883b30ea8e619ad3/vms/avm/vm_test.go#L342) do not call `vm.Shutdown()`. Is this a bug? Or are there conditions where it is not necessary/desirable to call `vm.Shutdown()`?

**Comment by StephenButtolph** [comment]
`vm.Ctx.Lock` should be held every time a VM function is called. With the potential exception of when an `http.Handler`'s `Handle` function is called. The locking provided here is specified by the wrapper around the handlers returned in `CreateHandlers`.

The VM interface expects the VM to be shutdown whenever the chain is being stopped (typically because the binary is exiting). For consistency, tests should call Shutdown on the VM.

**Comment by moreati** [comment]
> `vm.Ctx.Lock` should be held every time a VM function is ca

So because `Shutdown()` is a VM function, the lock is required to be held when `Shutdown()` is called. Hence it's safe to always call `vm.ctx.Lock.Unlock()` at the start of `Shutdown()`, and this note in https://golang.org/pkg/sync/#Mutex.Unlock isn't of concern

> It is a run-time error if m is not locked on entry to Unlock. 

Do I understand that correctly?

**Comment by moreati** [comment]
@StephenButtolph could you edit the bullet list at the top? To make it a checklist.

**Comment by StephenButtolph** [comment]
@moreati Updated the bullet list to be a checklist.

**Comment by moreati** [comment]
> @moreati Updated the bullet list to be a checklist.

Thanks, turns out I can't edit them. I'm done for now with #79
