### ISSUE TITLE
"terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]'" exception

### ISSUE THREAD

**Issue by sl-he** [ava-labs/gecko#85]
**Describe the bug**
Stopping after few seconds of activity

**To Reproduce**
1. Run `ava --public-ip=MY_PUBLIC_IP`
2. View exception

**Expected behavior**
Well, I was hoping it would start and work

**Operating System**
Ubuntu 18.04 LTS in CLI Mode

**Additional context**
```
terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]'
  what():  insufficient buffer: iostream error
SIGABRT: abort
PC=0x7fae7fb9b7bb m=4 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fae7fb9b7bb
stack: frame={sp:0x7fae7cf3d6b0, fp:0x0} stack=[0x7fae7c7411e8,0x7fae7cf40de8)
00007fae7cf3d5b0:  0000000000000000  0000000000000000
00007fae7cf3d5c0:  0000000000000000  0000000000000000
00007fae7cf3d5d0:  0000000000000000  0000000000000000
00007fae7cf3d5e0:  fffffffffffffff8  0000000000000001
00007fae7cf3d5f0:  0000000000000000  0000000000000000
00007fae7cf3d600:  0000000000000000  0000000000000030
00007fae7cf3d610:  0000000000000007  0000000000000000
00007fae7cf3d620:  0000000000000000  0000000000000000
00007fae7cf3d630:  0000000000000000  ffffffffff000000
00007fae7cf3d640:  0000000000000000  0000000000000000
00007fae7cf3d650:  0000000000000000  00007fae7fdf4b40
00007fae7cf3d660:  4000000000000000  0000000000000000
00007fae7cf3d670:  0000000000000000  0000000000000000
00007fae7cf3d680:  0000000000000000  0000000000000000
00007fae7cf3d690:  00007fae7cf3d8d0  00007fae7cf3d8d8
00007fae7cf3d6a0:  676e697472617473  726874206c6c6120
00007fae7cf3d6b0: <0000000000000000  0000000000000000
00007fae7cf3d6c0:  0000000000000004  0000000000000008
00007fae7cf3d6d0:  0000000000000000  000000c000c29274
00007fae7cf3d6e0:  0000000000000001  0000000000000003
00007fae7cf3d6f0:  0000000000000010  0000000000000008
00007fae7cf3d700:  0000000000000000  000000c000c29244
00007fae7cf3d710:  0000000000000001  000000000000000f
00007fae7cf3d720:  0000000000000001  0000000000000003
00007fae7cf3d730:  fffffffe7fffffff  ffffffffffffffff
00007fae7cf3d740:  ffffffffffffffff  ffffffffffffffff
00007fae7cf3d750:  ffffffffffffffff  ffffffffffffffff
00007fae7cf3d760:  ffffffffffffffff  ffffffffffffffff
00007fae7cf3d770:  ffffffffffffffff  ffffffffffffffff
00007fae7cf3d780:  ffffffffffffffff  ffffffffffffffff
00007fae7cf3d790:  ffffffffffffffff  ffffffffffffffff
00007fae7cf3d7a0:  ffffffffffffffff  ffffffffffffffff
runtime: unknown pc 0x7fae7fb9b7bb
stack: frame={sp:0x7fae7cf3d6b0, fp:0x0} stack=[0x7fae7c7411e8,0x7fae7cf40de8)
00007fae7cf3d5b0:  0000000000000000  0000000000000000
00007fae7cf3d5c0:  0000000000000000  0000000000000000
00007fae7cf3d5d0:  0000000000000000  0000000000000000
00007fae7cf3d5e0:  fffffffffffffff8  0000000000000001
00007fae7cf3d5f0:  0000000000000000  0000000000000000
00007fae7cf3d600:  0000000000000000  0000000000000030
00007fae7cf3d610:  0000000000000007  0000000000000000
00007fae7cf3d620:  0000000000000000  0000000000000000
00007fae7cf3d630:  0000000000000000  ffffffffff000000
00007fae7cf3d640:  0000000000000000  0000000000000000
00007fae7cf3d650:  0000000000000000  00007fae7fdf4b40
00007fae7cf3d660:  4000000000000000  0000000000000000
00007fae7cf3d670:  0000000000000000  0000000000000000
00007fae7cf3d680:  0000000000000000  0000000000000000
00007fae7cf3d690:  00007fae7cf3d8d0  00007fae7cf3d8d8
00007fae7cf3d6a0:  676e697472617473  726874206c6c6120
00007fae7cf3d6b0: <0000000000000000  0000000000000000
00007fae7cf3d6c0:  0000000000000004  0000000000000008
00007fae7cf3d6d0:  0000000000000000  000000c000c29274
00007fae7cf3d6e0:  0000000000000001  0000000000000003
00007fae7cf3d6f0:  0000000000000010  0000000000000008
00007fae7cf3d700:  0000000000000000  000000c000c29244
00007fae7cf3d710:  0000000000000001  000000000000000f
00007fae7cf3d720:  0000000000000001  0000000000000003
00007fae7cf3d730:  fffffffe7fffffff  ffffffffffffffff
00007fae7cf3d740:  ffffffffffffffff  ffffffffffffffff
00007fae7cf3d750:  ffffffffffffffff  ffffffffffffffff
00007fae7cf3d760:  ffffffffffffffff  ffffffffffffffff
00007fae7cf3d770:  ffffffffffffffff  ffffffffffffffff
00007fae7cf3d780:  ffffffffffffffff  ffffffffffffffff
00007fae7cf3d790:  ffffffffffffffff  ffffffffffffffff
00007fae7cf3d7a0:  ffffffffffffffff  ffffffffffffffff

goroutine 1 [syscall]:
runtime.cgocall(0xc628ae, 0xc001885b90, 0xc0017eda50)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc001885b60 sp=0xc001885b28 pc=0x42810b
github.com/ava-labs/salticidae-go._Cfunc_eventcontext_dispatch(0x216e6f0)
        _cgo_gotypes.go:979 +0x41 fp=0xc001885b90 sp=0xc001885b60 pc=0x91f0b1
github.com/ava-labs/salticidae-go.(*eventContext).Dispatch.func1(0xc0004c1060)
        /go/src/github.com/ava-labs/salticidae-go/event.go:34 +0x5e fp=0xc001885bd0 sp=0xc001885b90 pc=0x926fee
github.com/ava-labs/salticidae-go.(*eventContext).Dispatch(0xc0004c1060)
        /go/src/github.com/ava-labs/salticidae-go/event.go:34 +0x2b fp=0xc001885be8 sp=0xc001885bd0 pc=0x922eab
github.com/ava-labs/gecko/node.(*Node).Dispatch(...)
        /go/src/github.com/ava-labs/gecko/node/node.go:293
main.main()
        /go/src/github.com/ava-labs/gecko/main/main.go:86 +0xa56 fp=0xc001885f60 sp=0xc001885be8 pc=0xc5f126
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc001885fe0 sp=0xc001885f60 pc=0x45612e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc001885fe8 sp=0xc001885fe0 pc=0x4827c1

goroutine 3 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 5 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc00012a2a0)
        /go/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x134
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        /go/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x176

goroutine 6 [select]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc0001241e0)
        /go/src/github.com/syndtr/goleveldb/leveldb/session_util.go:189 +0x5f9
created by github.com/syndtr/goleveldb/leveldb.newSession
        /go/src/github.com/syndtr/goleveldb/leveldb/session.go:93 +0x2b4

goroutine 51 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc0006a8000)
        /go/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:91 +0xcd
created by github.com/syndtr/goleveldb/leveldb.openDB
        /go/src/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x40c

goroutine 52 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0006a8000)
        /go/src/github.com/syndtr/goleveldb/leveldb/db_state.go:101 +0xf6
created by github.com/syndtr/goleveldb/leveldb.openDB
        /go/src/github.com/syndtr/goleveldb/leveldb/db.go:149 +0x42e

goroutine 53 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc0006a8000)
        /go/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:836 +0x25d
created by github.com/syndtr/goleveldb/leveldb.openDB
        /go/src/github.com/syndtr/goleveldb/leveldb/db.go:155 +0x582

goroutine 54 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc0006a8000)
        /go/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:773 +0x150
created by github.com/syndtr/goleveldb/leveldb.openDB
        /go/src/github.com/syndtr/goleveldb/leveldb/db.go:156 +0x5a4

goroutine 57 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc00055e3d0, 0x8)
        /usr/local/go/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc00055e3c0)
        /usr/local/go/src/sync/cond.go:56 +0x9d
github.com/ava-labs/gecko/utils/logging.(*Log).run(0xc00001e0c0)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:68 +0x313
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00001e0c0, 0xc0004a53d0)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/utils/logging.New
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:42 +0x14e

goroutine 58 [select]:
github.com/ava-labs/gecko/nat.(*mapper).mapPort(0xc000690080, 0xc025b325b3)
        /go/src/github.com/ava-labs/gecko/nat/mapper.go:107 +0x15c
created by github.com/ava-labs/gecko/nat.(*mapper).MapPort
        /go/src/github.com/ava-labs/gecko/nat/mapper.go:81 +0x70

goroutine 115 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0017eb610, 0x0)
        /usr/local/go/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc0017eb600)
        /usr/local/go/src/sync/cond.go:56 +0x9d
github.com/ava-labs/gecko/utils/logging.(*Log).run(0xc001830c00)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:68 +0x313
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc001830c00, 0xc0017ed3b0)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/utils/logging.New
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:42 +0x14e

goroutine 59 [select]:
github.com/ava-labs/gecko/nat.(*mapper).mapPort(0xc000690080, 0xc025b225b2)
        /go/src/github.com/ava-labs/gecko/nat/mapper.go:107 +0x15c
created by github.com/ava-labs/gecko/nat.(*mapper).MapPort
        /go/src/github.com/ava-labs/gecko/nat/mapper.go:81 +0x70

goroutine 60 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc00055e410, 0x0)
        /usr/local/go/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc00055e400)
        /usr/local/go/src/sync/cond.go:56 +0x9d
github.com/ava-labs/gecko/utils/logging.(*Log).run(0xc00001e3c0)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:68 +0x313
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00001e3c0, 0xc0004a5660)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/utils/logging.New
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:42 +0x14e

goroutine 61 [IO wait]:
internal/poll.runtime_pollWait(0x7fae7c705d68, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000c16018, 0x72, 0x0, 0x0, 0xede0ae)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000c16000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc000c16000, 0xc0006b7c70, 0xc00009a380, 0x7fae7f974d98)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000c12020, 0xc0006b7ca0, 0x431cb8, 0x30)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000c12020, 0xe437e0, 0xc000c10180, 0xd81400, 0x179ba10)
        /usr/local/go/src/net/tcpsock.go:261 +0x47
net/http.(*Server).Serve(0xc000c14000, 0x1156280, 0xc000c12020, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2896 +0x286
net/http.(*Server).ListenAndServe(0xc000c14000, 0xc000c14000, 0xc00055ee00)
        /usr/local/go/src/net/http/server.go:2825 +0xb7
net/http.ListenAndServe(...)
        /usr/local/go/src/net/http/server.go:3080
github.com/ava-labs/gecko/api.(*Server).Dispatch(0x18f79d0, 0x0, 0x0)
        /go/src/github.com/ava-labs/gecko/api/server.go:48 +0x118
github.com/ava-labs/gecko/node.(*Node).initAPIServer.func2()
        /go/src/github.com/ava-labs/gecko/node/node.go:481 +0x32
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00001e0c0, 0xc0004c0a50)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/node.(*Node).initAPIServer
        /go/src/github.com/ava-labs/gecko/node/node.go:481 +0x207

goroutine 73 [select]:
github.com/ava-labs/gecko/utils/timer.(*Timer).Dispatch(0xc0004bb560)
        /go/src/github.com/ava-labs/gecko/utils/timer/timer.go:90 +0x1e1
github.com/ava-labs/gecko/utils/timer.(*TimeoutManager).Dispatch(...)
        /go/src/github.com/ava-labs/gecko/utils/timer/timeout_manager.go:40
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00001e0c0, 0xc0004c1150)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/networking.(*Handshake).Initialize
        /go/src/github.com/ava-labs/gecko/networking/handshake_handlers.go:156 +0x349

goroutine 74 [select]:
github.com/ava-labs/gecko/utils/timer.(*Timer).Dispatch(0xc0004bb5f0)
        /go/src/github.com/ava-labs/gecko/utils/timer/timer.go:90 +0x1e1
github.com/ava-labs/gecko/utils/timer.(*TimeoutManager).Dispatch(...)
        /go/src/github.com/ava-labs/gecko/utils/timer/timeout_manager.go:40
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00001e0c0, 0xc0004c1170)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/networking.(*Handshake).Initialize
        /go/src/github.com/ava-labs/gecko/networking/handshake_handlers.go:159 +0x3db

goroutine 75 [select]:
github.com/ava-labs/gecko/utils/timer.(*Repeater).Dispatch(0xc0004bb620)
        /go/src/github.com/ava-labs/gecko/utils/timer/repeater.go:58 +0x19a
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00001e0c0, 0xc0004c1190)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/networking.(*Handshake).Initialize
        /go/src/github.com/ava-labs/gecko/networking/handshake_handlers.go:162 +0x519

goroutine 106 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0002403d0, 0x0)
        /usr/local/go/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc0002403c0)
        /usr/local/go/src/sync/cond.go:56 +0x9d
github.com/ava-labs/gecko/utils/timer.(*Executor).Dispatch(0x18f7ec8)
        /go/src/github.com/ava-labs/gecko/utils/timer/executor.go:54 +0x190
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00001e0c0, 0xc0017e5520)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/networking.(*Voting).Initialize
        /go/src/github.com/ava-labs/gecko/networking/voting_handlers.go:84 +0x41b

goroutine 39 [select]:
github.com/ava-labs/gecko/utils/timer.(*Timer).Dispatch(0xc000c10a20)
        /go/src/github.com/ava-labs/gecko/utils/timer/timer.go:90 +0x1e1
github.com/ava-labs/gecko/utils/timer.(*TimeoutManager).Dispatch(...)
        /go/src/github.com/ava-labs/gecko/utils/timer/timeout_manager.go:40
github.com/ava-labs/gecko/snow/networking/timeout.(*Manager).Dispatch(...)
        /go/src/github.com/ava-labs/gecko/snow/networking/timeout/manager.go:28
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00001e0c0, 0xc0017e53e0)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/chains.New
        /go/src/github.com/ava-labs/gecko/chains/manager.go:147 +0xae

goroutine 25 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0017eae90, 0x3)
        /usr/local/go/src/runtime/sema.go:510 +0xf8
sync.(*Cond).Wait(0xc0017eae80)
        /usr/local/go/src/sync/cond.go:56 +0x9d
github.com/ava-labs/gecko/utils/logging.(*Log).run(0xc00001f8c0)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:68 +0x313
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00001f8c0, 0xc0017ece20)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/utils/logging.New
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:42 +0x14e

goroutine 26 [select]:
github.com/ava-labs/gecko/utils/timer.(*Timer).Dispatch(0xc001777bf0)
        /go/src/github.com/ava-labs/gecko/utils/timer/timer.go:90 +0x1e1
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00001f8c0, 0xc0017ecf50)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/vms/platformvm.(*VM).Initialize
        /go/src/github.com/ava-labs/gecko/vms/platformvm/vm.go:303 +0x434

goroutine 114 [select]:
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).Dispatch(0xc0004ba300)
        /go/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:41 +0x140
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00001f8c0, 0xc0017ed3a0)
        /go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/chains.(*manager).createSnowmanChain
        /go/src/github.com/ava-labs/gecko/chains/manager.go:524 +0x740

rax    0x0
rbx    0x6
rcx    0x7fae7fb9b7bb
rdx    0x0
rdi    0x2
rsi    0x7fae7cf3d6b0
rbp    0x7fae7fd20840
rsp    0x7fae7cf3d6b0
r8     0x0
r9     0x7fae7cf3d6b0
r10    0x8
r11    0x246
r12    0x7fae640017c0
r13    0x7fae7cf3db20
r14    0x216f060
r15    0x7fae7c47f010
rip    0x7fae7fb9b7bb
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

```

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Thanks for your report! Much appreciated.

This crash was because of the non-backwards compatible update we made to the networking portion of the node. Of course, in the future all the node's wont crash when we do an update ;)
Since this was a one-off thing, I'm going to close this issue.
