### ISSUE TITLE
[Crash] terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]' 

### ISSUE THREAD

**Issue by jzu** [ava-labs/gecko#86]
**Description**
Crash after 3 hours, running (IP is hidden):
```
$AVALABS/gecko/build/ava \
--public-ip=12.34.56.789 \
--xput-server-port=9255 \
--api-ipcs-enabled=true \
--http-port=9650 \
--http-tls-enabled=false \
--db-enabled=true \
--db-dir=$AVALABS/avash/stash/dragonstake/db1 \
--log-level=info \
--log-dir=$AVALABS/avash/stash/dragonstake/logs \
--staking-tls-key-file=$AVALABS/gecko/keys/staker.key \
--staking-tls-cert-file=$AVALABS/gecko/keys/staker.crt \
--staking-port=9158
```
Interesting (to me) excerpts from the output - [ava.log.gz](https://github.com/ava-labs/gecko/files/4502072/ava.log.gz) - captured using `... &> ava.log &`:
```
(...)
terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]'
  what():  insufficient buffer: iostream error
SIGABRT: abort
PC=0x7fa133a13e97 m=5 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fa133a13e97
stack: frame={sp:0x7fa12b7fa680, fp:0x0} stack=[0x7fa12affe1e8,0x7fa12b7fdde8)
00007fa12b7fa580:  00007fa12b7fa5b0  00007fa12b7fa5c0 
(...)
goroutine 1 [syscall]:
runtime.cgocall(0xbe9499, 0xc0006a9b90, 0xc0007798a0)
        /home/ava/.gvm/gos/go1.13.8/src/runtime/cgocall.go:128 +0x5b fp=0xc0006a9b60 sp=0xc0006a9b28 pc=0x42563b
github.com/ava-labs/salticidae-go._Cfunc_eventcontext_dispatch(0x33e09b0)
        _cgo_gotypes.go:979 +0x41 fp=0xc0006a9b90 sp=0xc0006a9b60 pc=0x89e151
(...)
goroutine 23 [select, 2 minutes]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc0002f8000)
        /home/ava/.gvm/pkgsets/go1.13.8/global/src/github.com/syndtr/goleveldb/leveldb/session_util.go:189 +0x5f9
created by github.com/syndtr/goleveldb/leveldb.newSession
        /home/ava/.gvm/pkgsets/go1.13.8/global/src/github.com/syndtr/goleveldb/leveldb/session.go:93 +0x2b4
(...)
```
**Operating System**
Ubuntu 18.04
4 * Intel(R) Atom(TM) CPU N2800 @ 1.86GHz
4 GB RAM

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Thanks for your report! Much appreciated.

This crash was because of the non-backwards compatible update we made to the networking portion of the node. Of course, in the future all the node's wont crash when we do an update ;)
Since this was a one-off thing, I'm going to close this issue.
