### ISSUE TITLE
Panicing due to: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by k0kk0k** [ava-labs/gecko#93]
### Gecko node crashed with log below:
**OS: Ubuntu 18.04**
**VPS: CPU 4 core, 8 Gb RAM, 200 Gb SSD**
```
2020-04-22 15:55:04.865039 [net info] <Conn fd=68 addr=<NetAddr 95.179.163.191:9801> mode=active> connect timeout
2020-04-22 15:55:04.865192 [net info] <Conn fd=71 addr=<NetAddr 78.168.90.52:9651> mode=active> connect timeout
2020-04-22 15:55:04.865259 [net info] 08403cbfd4: lost connection <Conn fd=68 addr=<NetAddr 95.179.163.191:9801> mode=active>
ERROR[04-22|15:55:04] /node/node.go#140: Error during async call: unable to connect
2020-04-22 15:55:04.865325 [net info] 08403cbfd4: lost connection <Conn fd=71 addr=<NetAddr 78.168.90.52:9651> mode=active>
ERROR[04-22|15:55:04] /node/node.go#140: Error during async call: unable to connect
INFO [04-22|15:55:07] <chain 11111111111111111111111111111111LpoYY> /vms/platformvm/vm.go#670: next scheduled event is at 2020-04-24 21:45:43 +0200 CEST (53h50m35.636941235s in the future)
INFO [04-22|15:55:07] <chain 11111111111111111111111111111111LpoYY> /vms/platformvm/vm.go#670: next scheduled event is at 2020-04-24 21:45:43 +0200 CEST (53h50m35.629528344s in the future)
FATAL[04-22|15:55:07] <chain 11111111111111111111111111111111LpoYY> /utils/logging/log.go#247: Panicing due to:
runtime error: invalid memory address or nil pointer dereference
From:
goroutine 131 [running]:
github.com/ava-labs/gecko/utils/logging.Stacktrace.String(0x450a00, 0xc001128b01, 0x7fb7c439c738)
        /home/ava/go/src/github.com/ava-labs/gecko/utils/logging/stack.go:20 +0x71
fmt.(*pp).handleMethods(0xc0031b7040, 0x73, 0x6400000001)
        /usr/local/go/src/fmt/print.go:630 +0x302
fmt.(*pp).printArg(0xc0031b7040, 0xdd9be0, 0xc0056501c8, 0x73)
        /usr/local/go/src/fmt/print.go:713 +0x206
fmt.(*pp).doPrintf(0xc0031b7040, 0xef57db, 0x1c, 0xc001129080, 0x2, 0x2)
        /usr/local/go/src/fmt/print.go:1030 +0x15b
fmt.Sprintf(0xef57db, 0x1c, 0xc001129080, 0x2, 0x2, 0xc000a45f40, 0x43)
        /usr/local/go/src/fmt/print.go:219 +0x66
github.com/ava-labs/gecko/utils/logging.(*Log).format(0xc00082cf00, 0x1, 0xef57db, 0x1c, 0xc001129080, 0x2, 0x2, 0x1, 0x5)
        /home/ava/go/src/github.com/ava-labs/gecko/utils/logging/log.go:165 +0x11a
github.com/ava-labs/gecko/utils/logging.(*Log).log(0xc00082cf00, 0x1, 0xef57db, 0x1c, 0xc001129080, 0x2, 0x2)
        /home/ava/go/src/github.com/ava-labs/gecko/utils/logging/log.go:138 +0x11f
github.com/ava-labs/gecko/utils/logging.(*Log).Fatal(...)
        /home/ava/go/src/github.com/ava-labs/gecko/utils/logging/log.go:180
github.com/ava-labs/gecko/utils/logging.(*Log).StopOnPanic(0xc00082cf00)
        /home/ava/go/src/github.com/ava-labs/gecko/utils/logging/log.go:247 +0xf4
panic(0xd98bc0, 0x19a0b20)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:48
github.com/ava-labs/gecko/database/versiondb.(*Database).Has(0x0, 0xc000aae120, 0x20, 0x20, 0x0, 0x0, 0x0)
        /home/ava/go/src/github.com/ava-labs/gecko/database/versiondb/db.go:40 +0x42
github.com/ava-labs/gecko/vms/components/state.(*state).Get(0xc0006bbc80, 0x116da80, 0x0, 0xfffffffffffffffd, 0xc0001ca380, 0xc0011292f8, 0x45a1dc, 0xc0007fe300, 0x300000002)
        /home/ava/go/src/github.com/ava-labs/gecko/vms/components/state/state.go:132 +0xc8
github.com/ava-labs/gecko/vms/components/state.(*state).GetTime(0xc0006bbc80, 0x116da80, 0x0, 0xc0001ca380, 0x1617ba110004cf00, 0x5ea04cbb, 0xc001129348, 0x4df5d6, 0x4decdd)
        /home/ava/go/src/github.com/ava-labs/gecko/vms/components/state/state.go:197 +0x56
github.com/ava-labs/gecko/vms/platformvm.(*VM).getTimestamp(0xc000688fc0, 0x116da80, 0x0, 0x0, 0x0, 0xd0, 0x0, 0x8)
        /home/ava/go/src/github.com/ava-labs/gecko/vms/platformvm/state.go:188 +0x5c
github.com/ava-labs/gecko/vms/platformvm.(*advanceTimeTx).SemanticVerify(0xc00261a420, 0x116da80, 0x0, 0x7fb7d13dd700, 0xc00120b6d0, 0x1, 0xd73d60, 0xc0007ea1b0, 0xc003e005e8)
        /home/ava/go/src/github.com/ava-labs/gecko/vms/platformvm/advance_time_tx.go:55 +0x9c
github.com/ava-labs/gecko/vms/platformvm.(*ProposalBlock).Verify(0xc00636f960, 0xc001129628, 0x1)
        /home/ava/go/src/github.com/ava-labs/gecko/vms/platformvm/proposal_block.go:99 +0xa2
github.com/ava-labs/gecko/snow/engine/snowman.(*Transitive).deliver(0xc0006cf340, 0x1167f80, 0xc00636f960)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/transitive.go:336 +0x10b
github.com/ava-labs/gecko/snow/engine/snowman.(*issuer).Update(...)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/issuer.go:43
github.com/ava-labs/gecko/snow/engine/snowman.(*issuer).Fulfill(0xc0031ae900, 0xc006130a20)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/issuer.go:22 +0xa8
github.com/ava-labs/gecko/snow/events.(*Blocker).Fulfill(0xc0006cf5b8, 0xc006130a20)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/events/blocker.go:32 +0x161
github.com/ava-labs/gecko/snow/engine/snowman.(*Transitive).deliver(0xc0006cf340, 0x1167f80, 0xc00636fc70)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/transitive.go:370 +0x36b
github.com/ava-labs/gecko/snow/engine/snowman.(*issuer).Update(...)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/issuer.go:43
github.com/ava-labs/gecko/snow/engine/snowman.(*issuer).Fulfill(0xc0031aec00, 0xc005dff980)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/issuer.go:22 +0xa8
github.com/ava-labs/gecko/snow/events.(*Blocker).Fulfill(0xc0006cf5b8, 0xc005dff980)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/events/blocker.go:32 +0x161
github.com/ava-labs/gecko/snow/engine/snowman.(*Transitive).deliver(0xc0006cf340, 0x1167ec0, 0xc0002fb680)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/transitive.go:365 +0x2b2
github.com/ava-labs/gecko/snow/engine/snowman.(*issuer).Update(0xc0031aeed0)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/issuer.go:43 +0x61
github.com/ava-labs/gecko/snow/events.(*Blocker).Register(0xc0006cf5b8, 0x115e440, 0xc0031aeed0)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/events/blocker.go:59 +0x289
github.com/ava-labs/gecko/snow/engine/snowman.(*Transitive).insert(0xc0006cf340, 0x1167ec0, 0xc0002fb680)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/transitive.go:272 +0x183
github.com/ava-labs/gecko/snow/engine/snowman.(*Transitive).insertFrom(0xc0006cf340, 0xc00340a7e0, 0x1167ec0, 0xc0002fb680, 0x1167ec0)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/transitive.go:231 +0xc2
github.com/ava-labs/gecko/snow/engine/snowman.(*Transitive).Put(0xc0006cf340, 0xc00340a7e0, 0x0, 0xc005f1fd40, 0xc0003b9548, 0x132, 0x132)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/transitive.go:88 +0x283
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).dispatchMsg(0xc00079fd70, 0x8, 0xc00340a7e0, 0x0, 0xc005f1fd40, 0xc0003b9548, 0x132, 0x132, 0x0, 0x0, ...)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:83 +0x434
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).Dispatch(0xc00079fd70)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:43 +0x2b3
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00082cf00, 0xc000af41e0)
        /home/ava/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/chains.(*manager).createSnowmanChain
        /home/ava/go/src/github.com/ava-labs/gecko/chains/manager.go:524 +0x740

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x99c8f2]

goroutine 131 [running]:
github.com/ava-labs/gecko/utils/logging.(*Log).StopOnPanic(0xc00082cf00)
        /home/ava/go/src/github.com/ava-labs/gecko/utils/logging/log.go:249 +0x11d
panic(0xd98bc0, 0x19a0b20)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:48
github.com/ava-labs/gecko/database/versiondb.(*Database).Has(0x0, 0xc000aae120, 0x20, 0x20, 0x0, 0x0, 0x0)
        /home/ava/go/src/github.com/ava-labs/gecko/database/versiondb/db.go:40 +0x42
github.com/ava-labs/gecko/vms/components/state.(*state).Get(0xc0006bbc80, 0x116da80, 0x0, 0xfffffffffffffffd, 0xc0001ca380, 0xc0011292f8, 0x45a1dc, 0xc0007fe300, 0x300000002)
        /home/ava/go/src/github.com/ava-labs/gecko/vms/components/state/state.go:132 +0xc8
github.com/ava-labs/gecko/vms/components/state.(*state).GetTime(0xc0006bbc80, 0x116da80, 0x0, 0xc0001ca380, 0x1617ba110004cf00, 0x5ea04cbb, 0xc001129348, 0x4df5d6, 0x4decdd)
        /home/ava/go/src/github.com/ava-labs/gecko/vms/components/state/state.go:197 +0x56
github.com/ava-labs/gecko/vms/platformvm.(*VM).getTimestamp(0xc000688fc0, 0x116da80, 0x0, 0x0, 0x0, 0xd0, 0x0, 0x8)
        /home/ava/go/src/github.com/ava-labs/gecko/vms/platformvm/state.go:188 +0x5c
github.com/ava-labs/gecko/vms/platformvm.(*advanceTimeTx).SemanticVerify(0xc00261a420, 0x116da80, 0x0, 0x7fb7d13dd700, 0xc00120b6d0, 0x1, 0xd73d60, 0xc0007ea1b0, 0xc003e005e8)
        /home/ava/go/src/github.com/ava-labs/gecko/vms/platformvm/advance_time_tx.go:55 +0x9c
github.com/ava-labs/gecko/vms/platformvm.(*ProposalBlock).Verify(0xc00636f960, 0xc001129628, 0x1)
        /home/ava/go/src/github.com/ava-labs/gecko/vms/platformvm/proposal_block.go:99 +0xa2
github.com/ava-labs/gecko/snow/engine/snowman.(*Transitive).deliver(0xc0006cf340, 0x1167f80, 0xc00636f960)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/transitive.go:336 +0x10b
github.com/ava-labs/gecko/snow/engine/snowman.(*issuer).Update(...)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/issuer.go:43
github.com/ava-labs/gecko/snow/engine/snowman.(*issuer).Fulfill(0xc0031ae900, 0xc006130a20)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/issuer.go:22 +0xa8
github.com/ava-labs/gecko/snow/events.(*Blocker).Fulfill(0xc0006cf5b8, 0xc006130a20)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/events/blocker.go:32 +0x161
github.com/ava-labs/gecko/snow/engine/snowman.(*Transitive).deliver(0xc0006cf340, 0x1167f80, 0xc00636fc70)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/transitive.go:370 +0x36b
github.com/ava-labs/gecko/snow/engine/snowman.(*issuer).Update(...)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/issuer.go:43
github.com/ava-labs/gecko/snow/engine/snowman.(*issuer).Fulfill(0xc0031aec00, 0xc005dff980)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/issuer.go:22 +0xa8
github.com/ava-labs/gecko/snow/events.(*Blocker).Fulfill(0xc0006cf5b8, 0xc005dff980)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/events/blocker.go:32 +0x161
github.com/ava-labs/gecko/snow/engine/snowman.(*Transitive).deliver(0xc0006cf340, 0x1167ec0, 0xc0002fb680)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/transitive.go:365 +0x2b2
github.com/ava-labs/gecko/snow/engine/snowman.(*issuer).Update(0xc0031aeed0)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/issuer.go:43 +0x61
github.com/ava-labs/gecko/snow/events.(*Blocker).Register(0xc0006cf5b8, 0x115e440, 0xc0031aeed0)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/events/blocker.go:59 +0x289
github.com/ava-labs/gecko/snow/engine/snowman.(*Transitive).insert(0xc0006cf340, 0x1167ec0, 0xc0002fb680)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/transitive.go:272 +0x183
github.com/ava-labs/gecko/snow/engine/snowman.(*Transitive).insertFrom(0xc0006cf340, 0xc00340a7e0, 0x1167ec0, 0xc0002fb680, 0x1167ec0)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/transitive.go:231 +0xc2
github.com/ava-labs/gecko/snow/engine/snowman.(*Transitive).Put(0xc0006cf340, 0xc00340a7e0, 0x0, 0xc005f1fd40, 0xc0003b9548, 0x132, 0x132)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/engine/snowman/transitive.go:88 +0x283
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).dispatchMsg(0xc00079fd70, 0x8, 0xc00340a7e0, 0x0, 0xc005f1fd40, 0xc0003b9548, 0x132, 0x132, 0x0, 0x0, ...)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:83 +0x434
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).Dispatch(0xc00079fd70)
        /home/ava/go/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:43 +0x2b3
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc00082cf00, 0xc000af41e0)
        /home/ava/go/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/chains.(*manager).createSnowmanChain
        /home/ava/go/src/github.com/ava-labs/gecko/chains/manager.go:524 +0x740

```

**Comment by danlaine** [comment]
@k0kk0k Thanks for reporting this. Looking into it now.

**Comment by danlaine** [comment]
Copied below is the implementation of `func (pb *ProposalBlock) Verify()` in `vms/platformvm/proposal_block.go`:

```
func (pb *ProposalBlock) Verify() error {
	// pdb is the database if this block's parent is accepted
	var pdb database.Database
	parent := pb.parentBlock()
	// The parent of a proposal block (ie this block) must be a decision block
	if parent, ok := parent.(decision); ok {
		pdb = parent.onAccept()
	} else {
		return errInvalidBlockType
	}

	var err error
	pb.onCommitDB, pb.onAbortDB, pb.onCommitFunc, pb.onAbortFunc, err = pb.Tx.SemanticVerify(pdb)
	if err != nil {
		return err
	}

	pb.vm.currentBlocks[pb.ID().Key()] = pb
	parent.addChild(pb)
	return nil
}
```

The stacktrace tells us `SemanticVerify` is given a `nil` argument, which means that variable `pdb` is `nil`, which means that this block's parent is returning `nil` when `onAccept` is called.

The implementation of `onAccept()`:
```
func (cdb *CommonDecisionBlock) onAccept() database.Database {
	if cdb.Status().Decided() {
		return cdb.vm.DB
	}
	return cdb.onAcceptDB
}
```
It seems unlikely that `cdb.vm.DB` is `nil` so this method is probably returning `cdb.onAcceptDB`, which is uninitialized. 

There are 4 blocks that embed `commonDecisionBlock`: `Abort`, `AtomicBlock`, `Commit`, and `StandardBlock`. The bug likely passes through the `Verify` method (which sets `onAcceptDB`) on one of these blocks. From there, it's probably in some proposal block's `onAccept` or `onAbort` method. Don't have time right now to trace the bug any further than that.

**Comment by StephenButtolph** [comment]
If we end up ruling out the VM from having the bug, this error could also be caused by Snowman not properly calling Verify on the parent block, or calling Verify on a child block whose parent was determined as invalid.

**Comment by danlaine** [comment]
Yeah, that's possible. I think it's a lot more likely that the bug is in the VM, though.

**Comment by fabiux82** [comment]
I had a similar crash with the same error but the last function in log is createAvalancheChain and not createSnowmanChain:

```
FATAL[04-24|11:21:02] <chain 4ktRjsAKxgMr2aEzv9SWmrU7Xk5FniHUrVCX4P1TZSfTLZWFM> /utils/logging/log.go#247: Panicing due to:
runtime error: invalid memory address or nil pointer dereference
From:                                                                                                                                                     [32/99657]
goroutine 105 [running]:
github.com/ava-labs/gecko/utils/logging.Stacktrace.String(0x450a00, 0xc000a8b301, 0x7f9aa3890b88)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/stack.go:20 +0x71
fmt.(*pp).handleMethods(0xc00678c820, 0x73, 0x6400000001)
        /usr/local/go/src/fmt/print.go:630 +0x302
fmt.(*pp).printArg(0xc00678c820, 0xddb5a0, 0xc005e8b140, 0x73)
        /usr/local/go/src/fmt/print.go:713 +0x206
fmt.(*pp).doPrintf(0xc00678c820, 0xef7362, 0x1c, 0xc000a8b8c0, 0x2, 0x2)
        /usr/local/go/src/fmt/print.go:1030 +0x15b
fmt.Sprintf(0xef7362, 0x1c, 0xc000a8b8c0, 0x2, 0x2, 0xc006064d20, 0x46)
        /usr/local/go/src/fmt/print.go:219 +0x66
github.com/ava-labs/gecko/utils/logging.(*Log).format(0xc0007fc840, 0x1, 0xef7362, 0x1c, 0xc000a8b8c0, 0x2, 0x2, 0x1, 0xc005e8b140)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:165 +0x11a
github.com/ava-labs/gecko/utils/logging.(*Log).log(0xc0007fc840, 0x1, 0xef7362, 0x1c, 0xc000a8b8c0, 0x2, 0x2)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:138 +0x11f
github.com/ava-labs/gecko/utils/logging.(*Log).Fatal(...)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:180
github.com/ava-labs/gecko/utils/logging.(*Log).StopOnPanic(0xc0007fc840)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:247 +0xf4
panic(0xd9a520, 0x19a3b20)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/ava-labs/gecko/snow/engine/avalanche/state.(*uniqueVertex).Parents(0xc0060514a0, 0x30, 0x30, 0xc00606e9c0)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/state/unique_vertex.go:111 +0x3c
github.com/ava-labs/gecko/snow/engine/avalanche.(*vertexJob).MissingDependencies(0xc00606e9c0, 0x42f258)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/vertex_job.go:40 +0x46
github.com/ava-labs/gecko/snow/engine/common/queue.(*Jobs).Push(0xc0008630e0, 0x1160180, 0xc00606e9c0, 0x1, 0x0)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/common/queue/jobs.go:49 +0x35
github.com/ava-labs/gecko/snow/engine/avalanche.(*bootstrapper).storeVertex(0xc0000352e8, 0x1169c60, 0xc0023c2b00)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/bootstrapper.go:163 +0x39f
github.com/ava-labs/gecko/snow/engine/avalanche.(*bootstrapper).addVertex(0xc0000352e8, 0x1169c60, 0xc0023c2b00)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/bootstrapper.go:141 +0x3f
github.com/ava-labs/gecko/snow/engine/avalanche.(*bootstrapper).Put(0xc0000352e8, 0xc00084e320, 0xc276, 0xc002fd04a0, 0xc00185ea48, 0x54, 0x54)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/bootstrapper.go:106 +0x2a4
github.com/ava-labs/gecko/snow/engine/avalanche.(*Transitive).Put(0xc000035200, 0xc00084e320, 0xc276, 0xc002fd04a0, 0xc00185ea48, 0x54, 0x54)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/transitive.go:87 +0x2e2
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).dispatchMsg(0xc000863fb0, 0x8, 0xc00084e320, 0xc276, 0xc002fd04a0, 0xc00185ea48, 0x54, 0x54, 0x0, 0x0, 
...)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:83 +0x434
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).Dispatch(0xc000863fb0)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:43 +0x2b3
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc0007fc840, 0xc0008556b0)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/chains.(*manager).createAvalancheChain
        /home/us/gopath/src/github.com/ava-labs/gecko/chains/manager.go:438 +0x8a2

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9b16ac]

goroutine 105 [running]:
github.com/ava-labs/gecko/utils/logging.(*Log).StopOnPanic(0xc0007fc840)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:249 +0x11d
panic(0xd9a520, 0x19a3b20)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/ava-labs/gecko/snow/engine/avalanche/state.(*uniqueVertex).Parents(0xc0060514a0, 0x30, 0x30, 0xc00606e9c0)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/state/unique_vertex.go:111 +0x3c
github.com/ava-labs/gecko/snow/engine/avalanche.(*vertexJob).MissingDependencies(0xc00606e9c0, 0x42f258)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/vertex_job.go:40 +0x46
github.com/ava-labs/gecko/snow/engine/common/queue.(*Jobs).Push(0xc0008630e0, 0x1160180, 0xc00606e9c0, 0x1, 0x0)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/common/queue/jobs.go:49 +0x35
github.com/ava-labs/gecko/snow/engine/avalanche.(*bootstrapper).storeVertex(0xc0000352e8, 0x1169c60, 0xc0023c2b00)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/bootstrapper.go:163 +0x39f
github.com/ava-labs/gecko/snow/engine/avalanche.(*bootstrapper).addVertex(0xc0000352e8, 0x1169c60, 0xc0023c2b00)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/bootstrapper.go:141 +0x3f
github.com/ava-labs/gecko/snow/engine/avalanche.(*bootstrapper).Put(0xc0000352e8, 0xc00084e320, 0xc276, 0xc002fd04a0, 0xc00185ea48, 0x54, 0x54)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/bootstrapper.go:106 +0x2a4
github.com/ava-labs/gecko/snow/engine/avalanche.(*Transitive).Put(0xc000035200, 0xc00084e320, 0xc276, 0xc002fd04a0, 0xc00185ea48, 0x54, 0x54)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/engine/avalanche/transitive.go:87 +0x2e2
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).dispatchMsg(0xc000863fb0, 0x8, 0xc00084e320, 0xc276, 0xc002fd04a0, 0xc00185ea48, 0x54, 0x54, 0x0, 0x0,
...)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:83 +0x434
github.com/ava-labs/gecko/snow/networking/handler.(*Handler).Dispatch(0xc000863fb0)
        /home/us/gopath/src/github.com/ava-labs/gecko/snow/networking/handler/handler.go:43 +0x2b3
github.com/ava-labs/gecko/utils/logging.(*Log).RecoverAndPanic(0xc0007fc840, 0xc0008556b0)
        /home/us/gopath/src/github.com/ava-labs/gecko/utils/logging/log.go:254 +0x57
created by github.com/ava-labs/gecko/chains.(*manager).createAvalancheChain
        /home/us/gopath/src/github.com/ava-labs/gecko/chains/manager.go:438 +0x8a2
```

**Comment by bb-2** [comment]
@fabiux82's error could be produced during bootstrapping for blocks passed to the Put function that have parentBlocks containing an empty ID. The [VM.ParseBlock](https://github.com/ava-labs/gecko/blob/master/vms/spchainvm/vm.go#L165) function will call [startVerify](https://github.com/ava-labs/gecko/blob/master/vms/spchainvm/block.go#L40) but it wont perform the [verify](https://github.com/ava-labs/gecko/blob/master/vms/spchainvm/block.go#L48) check that would guard against empty parent ID's.

**Comment by bb-2** [comment]
I think it's also happening in the avalanche context where vertex parentID's are checked for [sorting and uniqueness](https://github.com/ava-labs/gecko/blob/master/snow/engine/avalanche/state/vertex.go#L47) but not for the presence of parentID's

**Comment by StephenButtolph** [comment]
@fabiux82 Your error seems to be stemming from a separate module, would you mind creating a new issue for your error?

**Comment by fabiux82** [comment]
@StephenButtolph done: https://github.com/ava-labs/gecko/issues/114
